"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
import pymysql
# python-dotenv 라이브러리 가져오기
from dotenv import load_dotenv
from pathlib import Path

# 1. 프로젝트 루트에 있는 .env 파일을 읽어서 환경변수로 등록
load_dotenv()

# 2. MySQLdb 대신 pymysql을 MySQL 드라이버로 사용하도록 설정
pymysql.install_as_MySQLdb()

# 커스텀 유저 모델을 사용하기 위해 get_user_model 함수를 가져옵니다.
AUTH_USER_MODEL = 'timefit.User'

# .env 파일에서 구글 키값을 가져와 장고 변수에 안전하게 보관합니다.
GOOGLE_CLIENT_ID = os.getenv("GOOGLE_CLIENT_ID")
GOOGLE_SECRET_KEY = os.getenv("GOOGLE_SECRET_KEY")

# 구글 로그인 버튼 누르면 확인 창 없이 즉시 구글 계정 선택창으로 이동
SOCIALACCOUNT_LOGIN_ON_GET = True

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-hkkunn#gmbvva&&^sfsp2n3jkxv&&6f$3xn-8l5xt+))^32l**'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework', # DRF(API관련) 설치 후 추가
    'timefit',

    # django-allauth 필수 패키지 등록
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    # 우리가 연동할 구글 API 프로바이더 등록
    'allauth.socialaccount.providers.google',
]

# allauth는 내부적으로 다중 사이트 관리 기능을 쓰므로 ID를 1로 지정합니다.
SITE_ID = 1

# 3. django-allauth 세부 기능 설정 (파일 맨 아래 추가)
# 로그인/로그아웃 성공 시 이동할 URL (일본어 화면 뷰 라우팅 명칭)
LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'home'

# 일반 가입 시 이메일 필수 여부 및 로그인 방식 설정
ACCOUNT_EMAIL_REQUIRED = True            # 이메일 필수 입력
ACCOUNT_USERNAME_REQUIRED = True         # 유저명 필수 입력
ACCOUNT_AUTHENTICATION_METHOD = 'username_email' # 아이디 또는 이메일 둘 다로 로그인 가능
ACCOUNT_EMAIL_VERIFICATION = 'none'      # 개발 단계이므로 이메일 인증 메일 발송은 끕니다.

# 구글 소셜 가입 시 유저명(username) 설정을 어떻게 할지 세팅
SOCIALACCOUNT_AUTO_SIGNUP = False        
# 구글 로그인 후 추가 정보(유저명)를 입력하는 Form(우리가 짠 것)을 거치게함

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST'),
        'PORT': os.getenv('DB_PORT'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# 1. AUTHENTICATION_BACKENDS 설정 추가
AUTHENTICATION_BACKENDS = [
    # Django 기본 아이디/비밀번호 인증 백엔드
    'django.contrib.auth.backends.ModelBackend',
    # django-allauth 전용 인증 백엔드 (구글 소셜 로그인용)
    'allauth.account.auth_backends.AuthenticationBackend',
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'ja'

TIME_ZONE = 'Asia/Tokyo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
