# Generated by Django 6.0.6 on 2026-06-15 01:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timefit', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'ユーザー', 'verbose_name_plural': 'ユーザー管理'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
        migrations.AddField(
            model_name='user',
            name='reset_time',
            field=models.TimeField(default='00:00', verbose_name='更新基準時間'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='登録日時'),
        ),
        migrations.AlterField(
            model_name='user',
            name='google_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Google固有ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_google_user',
            field=models.BooleanField(default=False, verbose_name='Google連携ユーザー'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='プロフィール画像URL'),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='カテゴリ名')),
                ('color', models.CharField(default='#3498db', max_length=7, verbose_name='カラーコード')),
                ('is_default', models.BooleanField(default=False, verbose_name='デフォルト表示')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'カテゴリ',
                'verbose_name_plural': 'カテゴリ管理',
                'db_table': 'categories',
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255, verbose_name='タスク内容')),
                ('is_completed', models.BooleanField(default=False, verbose_name='完了ステータス')),
                ('estimated_time', models.PositiveIntegerField(blank=True, null=True, verbose_name='予想時間(分)')),
                ('actual_time', models.PositiveIntegerField(blank=True, null=True, verbose_name='実績時間(分)')),
                ('target_date', models.DateField(verbose_name='実施予定日')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完了日時')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='todos', to='timefit.category', verbose_name='カテゴリ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todos', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'タスク',
                'verbose_name_plural': 'タスク管理',
                'db_table': 'todos',
                'ordering': ['target_date', '-created_at'],
            },
        ),
    ]
