# Generated by Django 6.0.6 on 2026-06-18 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timefit', '0002_alter_user_options_remove_user_bio_user_reset_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='is_migrated',
            field=models.BooleanField(default=False),
        ),
    ]
